name: Metrics
on:
  # Atualiza a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token não é necessário aqui se usar o GITHUB_TOKEN padrão para métricas básicas
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções visuais
          user: EduardoRGS
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_lines: yes
